name: Build Release Artifacts
on:
  release:
    types: [ created ]
jobs:
  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          tools-deps: 'latest'
      - run: clj -T:build uber
      - run: jpackage @jpackage/common @jpackage/mac
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: vbr-gerador-docs-1.0.dmg
          asset_name: vbr-gerador-docs-1.0.dmg
          asset_content_type: application/x-apple-diskimage
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: iwr -useb download.clojure.org/install/win-install-1.12.0.1479.ps1 | iex
      - run: clj -T:build uber
      - run: jpackage @jpackage/common @jpackage/windows
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: vbr-gerador-docs-1.0.exe
          asset_name: vbr-gerador-docs-1.0.exe
          asset_content_type: application/vnd.microsoft.portable-executable