name: Build Release Artifacts
on:
  release:
    types: [ created ]
jobs:
  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 'latest'
      - run: clojure -T:build uber
      - run: jpackage @jpackage/common @jpackage/mac
      - uses: actions/upload-artifact@v4
        with:
          name: vbr-gerador-docs-1.0.dmg
          path: vbr-gerador-docs-1.0.dmg
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 'latest'
      - run: clojure -A:uberjar
      - run: jpackage @jpackage/common @jpackage/windows
      - uses: actions/upload-artifact@v4
        with:
          name: vbr-gerador-docs-1.0.exe
          path: vbr-gerador-docs-1.0.exe